---
- name: Docker | Include vars
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Docker | Check if Docker is installed
  win_service:
    name: Docker
  register: docker_service

- name: Docker | Stop docker service before removal
  win_service:
    name: Docker
    state: stopped

- name: Docker | Remove docker files
  win_shell: |
    $ErrorActionPreference = "Stop"
    Remove-Item "C:\\Program Files\\Docker" -Recurse
  when: docker_service.exists

- name: Docker | Install docker
  block:
    - name: Docker | Install docker
      include_tasks: ./install_docker.yml
