---
- name: Flannel | Enable bridged IPv4 traffic
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: Flannel | Download flannel yaml
  get_url:
    url: "{{ flannel_download_links.kube_flannel_vxlan }}"
    dest: /root/kube-flannel.yml
    mode: 0644
  when: FLANNEL_MODE == "overlay"

- name: Flannel | Download flannel yaml
  get_url:
    url: "{{ flannel_download_links.kube_flannel_l2bridge }}"
    dest: /root/kube-flannel.yml
    mode: 0644
  when: FLANNEL_MODE == "host-gw"

- name: Flannel | Apply flannel yaml
  shell: |
    kubectl apply -f /root/kube-flannel.yml

- name: Flannel | Download node-selector-patch.yml
  get_url:
    url: "{{ flannel_download_links.node_selector_patch }}"
    dest: /root/node-selector-patch.yml
    mode: 0644

- name: Flannel | Apply NodeSelector to kube-flannel-ds
  shell: |
    kubectl patch ds/kube-flannel-ds-amd64 --patch "$(cat /root/node-selector-patch.yml)" -n=kube-system
