---

- name: Docker | Uninstall Docker Package
  win_shell: |
    Uninstall-Package -Name docker -ProviderName DockerMsftProvider
    Uninstall-Module -Name DockerMsftProvider

- name: Docker | Remove current default nat network
  win_shell: |
    Get-HNSNetwork | Where-Object { $_.Name -eq "nat" } | Remove-HNSNetwork

- name: Reinstall required features that may have been removed with Docker
  include_tasks: "{{ playbook_dir }}/roles/windows/requirements/tasks/main.yml"

- name: Windows | Expect reboot_required to false
  set_fact:
    reboot_required: false

- name: Windows | Installing Required features
  win_feature:
    name: "{{item}}"
    state: present
  register: features_installed
  with_items:
    - Containers

- name: Windows | Checking if reboot_required
  set_fact:
    reboot_required: true
  with_items:
    - "{{features_installed.results}}"
  loop_control:
    label: "{{item.item}}"
  when: item.reboot_required

- name: Windows | Reboot the node
  win_reboot:
  when: reboot_required